version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.1
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@18.0.0
  build:
    commands:
      - echo "Building Angular Project"
      - ng build --configuration production
  post_build:
    commands:
      - echo "Checking built files in dist/aws-hosting/"
      - ls -la dist/
      - ls -la dist/aws-hosting/
      - echo "Syncing to S3 bucket..."
      - aws s3 sync dist/aws-hosting/ s3://sw-dev-angular-app --delete --exact-timestamps --debug
