version: 0.2
phases :
  install: 
    runtime-versions:
      nodejs: 20.15.1
    commands:
      - echo "Installing dpendencies.."
      - npm install
      - npm install -g @angular/cli@18.0.0
  build:
    commands:
      - echo "Building Angular Project"
      - ng build --configuration production
  post_build:
    commands:
      - echo "Updating files into S3 bucket..."
      - aws s3 sync dist/aws-hosting/ s3://sw-dev-angular-app --delete