version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.1
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@18.0.0

  build:
    commands:
      - echo "Building Angular Project"
      - ng build --configuration production

  post_build:
    commands:
      - echo "Uploading only the browser build output..."
      - aws s3 sync dist/aws-hosting/browser/ s3://sw-dev-angular-app --delete
      - echo "Invalidating CloudFront..."
      - aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"

